name: Deploy from source repo

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Setup nodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Puedes ajustar la versión que necesites
      # Clonamos el repositorio adicional en la rama main
      - name: Clone Additional Repository
        run: git clone -b main https://github.com/jaimesempere/angular-poc.git
      # Movemos el contenido de la carpeta angular-poc a la raíz y eliminamos la carpeta original
      - name: Move angular-poc to root
        run: |
          mv angular-poc/* .
          rm -rf angular-poc
          cp -f context/package.json ./
          rm -rf context
          rm package-lock.json
          ls -ltra
      # Install dependencies
      - name: Install deps
        run: npm i
      # Build app for production
      - name: Build app bundle
        run: npm run build:prod
      # Route file renaming
      - name: Rename index for routing
        run: mv dist/angular-poc/index.html dist/angular-poc/404.html
      - name: Rename build folder to angular-github-actions-mirror1
        run: mv dist/angular-poc dist/angular-github-actions-mirror1
      # Deploy to Github pages
      - name: Deploy to Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist/angular-github-actions-mirror1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
